### ISSUE TITLE
Support indirection just like ModManager

### ISSUE THREAD

**Issue by pardeike** [KiameV/rimworld-modsync-rw#11]
Right now, I always update both files, Fluffy’s Mod Manager and this mods files with a build script. Not only is this adding an extra step to the build process, it also isn’t necessary anymore for ModManager because of this fix I just learned about: https://github.com/pardeike/HarmonyRimWorld/pull/14

My feature request is to make ModSync do the same as ModManager by letting me define /latest in the manifest and use the same code to fetch the version information. As a result I can continue to have a version checked in on master that is not released yet without it being shown to users until I create a release. It would also mean that I and other mod authors don’t have to keep updating these files.

**Comment by KiameV** [comment]
I'll do one better, I'll just support Manifest.xml. Since neither ModSync.xml nor Version.xml never took off I've changed the code to check if Manifest.xml exists. If it doesn't then it'll fall back to ModSync then Version.

In short you can delete the ModSync.xml from here on and the Manifest.xml will be used.

Version 1.2.1.0 of modsync released.

**Comment by pardeike** [comment]
Awesome!!
