### ISSUE TITLE
Game breaking UI bug

### ISSUE THREAD

**Issue by DingoDjango** [KiameV/rimworld-modsync-rw#2]
The ModSync main menu button is not aligned with the Mods main menu button. As show here:

![horror](https://user-images.githubusercontent.com/3172881/41784624-f1c9dda4-7648-11e8-9d4d-c9dd95512746.png)

This makes the game literally unplayable for 99.9% of users when using ModSync.

**Comment by KiameV** [comment]
!!!!
I'll take a look at that tonight.

**Comment by KiameV** [comment]
So they are aligned on my monitor (1440 vertical res). I do see if i go to windowed mode and resize the window vertically they do become misaligned.

The base game's drawer stores the buttons in a list then in another method draws the list from an offset. (MainMenuDrawer.DoMainMenuControls is the class.method). My attempt to match the location is:
`float y = ((rect.yMax + rect.yMin) * .49f) + 2.0f;`
I can tell this is inaccurate but for now it's the best i have. I am going to close this but I will keep this in mind if I have some time to play around with this again.

- I _could_ add the ModSync button to the list but I do not want to add a possibility of vertically overflowing the buttons on some setups.

**Comment by KiameV** [comment]
Eureka!

I looked at the problem one more time and noticed the other buttons stayed centered through the process of vertically resizing the window.
Based off this I reformatted my equation to be:
`float y = ((rect.yMax + rect.yMin) * 0.5f) - 8.5f;`

The fix for this issue will be included in the next release. (I was on the right track previously but 0.49 was a bad multiplier (not sure what i was thinking originally))
